Repository wecode-bootcamp-korea/22-2nd-22percent-frontend, pull requests merged in 2021-07, with the labels that each got.

#1 [22기 정빛열음] Add: nav 레이아웃 완료
  src/components/Nav/Nav.js
  src/components/Nav/SubNav/SubNav.js
  src/components/Nav/SubNav/SubNavItem.js
  src/pages/Main/Main.js
  src/styles/globalStyle.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#2 [22기 정빛열음] Add: footer 레이아웃 완료
  src/components/Footer/Footer.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#4 [22기 황소미] Sign in and Sign up layout completed
  package-lock.json
  package.json
  src/components/Kakao/OAuth.js
  src/components/Login/Button.js
  src/components/Login/Input.js
  src/pages/SignIn/SignIn.js
  src/pages/SignUp/SignUp.js
  src/styles/theme.js
  yarn.lock
Labels: Status: 리뷰 요청

#5 [22기 정빛열음] Modify: 스타일 초기 설정 수정
  src/styles/globalStyle.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#3 [22기 정빛열음] Add: Main, RealEstate 레이아웃 완료
  public/images/kakao-ch-banner.png
  src/components/ProductList/ProductItem/ProductItem.js
  src/components/ProductList/ProductList.js
  src/pages/Main/AccBox/AccBox.js
  src/pages/Main/Main.js
  src/pages/Main/MainSlide/MainSlide.js
  src/pages/Main/MainSlide/MainSlideItem/MainSlideItem.js
  src/pages/RealEstate/PastProductList/PastProductItem/PastProductItem.js
  src/pages/RealEstate/PastProductList/PastProductList.js
  src/pages/RealEstate/RealEstate.js
Labels: Status: Accepted

#7 [22기 황소미] 글로벌스타일 폰트 수정
  src/styles/globalStyle.js
Labels: Status: 리뷰 요청

#6 [22기 황소미] 마이페이지 투자내역 레이아웃 구현 완료
  package-lock.json
  package.json
  public/data/overview.json
  public/image/a.png
  public/image/b.png
  public/image/c.png
  public/image/d.png
  public/image/kakaofriend.png
  src/Routes.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/Overview/ChartOption.js
  src/pages/MyPage/Overview/InvestContent.js
  src/pages/MyPage/Overview/Overview.js
  src/pages/MyPage/Overview/OverviewLeftBottom.js
  src/pages/MyPage/Overview/OverviewLeftTop.js
  src/pages/MyPage/Overview/OverviewRightBottom.js
  src/pages/MyPage/Overview/OverviewRightTop.js
  src/pages/MyPage/Overview/PortfolioTable.js
  src/utils.js
Labels: Status: 리뷰 요청

#14 [22기 정빛열음] footer: class => className
  src/components/Footer/Footer.js
Labels: Status: 리뷰 요청

#11 [22기 정빛열음] Add: 개인신용 페이지 레이아웃
  src/Routes.js
  src/pages/Individual/Individual.js
  src/pages/Individual/IndividualFilter/IndividualFilter.js
  src/pages/Individual/IndividualFilter/IndividualFilterBar/IndividualFilterBar.js
  src/pages/Individual/IndividualFilter/filterRange.js
  src/pages/Individual/IndividualItem/IndividualItem.js
Labels: Status: Accepted

#9 [22기 정빛열음] Add: 라우팅 진행
  src/components/Nav/Nav.js
  src/components/Nav/SubNav/SubNav.js
  src/components/Nav/SubNav/SubNavItem.js
  src/components/Nav/SubNav/navTabList.js
  src/config.js
Labels: Status: 리뷰 요청

#10 [22기 황소미] 투자내역 페이지 레이아웃 및 기능 구현 완료
  public/data/history.json
  public/image/a+.png
  public/image/a-.png
  public/image/b+.png
  public/image/b-.png
  public/image/c+.png
  public/image/c-.png
  public/image/d+.png
  src/Routes.js
  src/pages/MyPage/History/History.js
  src/pages/MyPage/History/HistoryHeader.js
  src/pages/MyPage/History/HistoryTable.js
  src/pages/MyPage/History/PaymentSummaryList.js
Labels: Status: Accepted, Status: 수정 요청

#13 [22기 황소미] 로그인 기능 코멘트 반영(URGENT ㅠㅠ)
  public/index.html
  src/Validation/Validation.js
  src/components/Kakao/OAuth.js
  src/components/Login/Button.js
  src/components/Login/Input.js
  src/config.js
  src/pages/SignIn/SignIn.js
  src/pages/SignUp/SignUp.js
Labels: Status: 리뷰 요청

#8 [22기 장운서] 부동산 상품 detail page 레이아웃 및 지도,그래프 구현 수정완료
  public/index.html
  src/config.js
  src/pages/Main/MainSlide/MainSlide.js
  src/pages/RealEstateDetail/Chart/lineChart.js
  src/pages/RealEstateDetail/Chart/pieChart.js
  src/pages/RealEstateDetail/ControllerWrap/ControllerWrap.js
  src/pages/RealEstateDetail/Deal/Deal.js
  src/pages/RealEstateDetail/Deal/DealStyle.js
  src/pages/RealEstateDetail/Deal/DealWrap/DealDetail.js
  src/pages/RealEstateDetail/Deal/DealWrap/DealInfo.js
  src/pages/RealEstateDetail/Deal/DealWrap/DealOutLine.js
  src/pages/RealEstateDetail/Deal/DealWrap/DealPoint.js
  src/pages/RealEstateDetail/Deal/DealWrap/DealSecurity.js
  src/pages/RealEstateDetail/DealHeader/DealHeader.js
  src/pages/RealEstateDetail/DealHeader/DealInfo.js
  src/pages/RealEstateDetail/KakaoMapScript.js
  src/pages/RealEstateDetail/RealEstateDetail.js
  src/pages/RealEstateDetail/SVGImg/Home.svg
  src/pages/RealEstateDetail/SVGImg/Macker.svg
  src/pages/RealEstateDetail/Slide/Slide.js
  src/styles/globalStyle.js
  yarn.lock
Labels: Status: Accepted

#21 [22기 장운서] API 연결하는 부분에서 오류로인한 나머지 않나오는 부분때문에 수정
  src/pages/RealEstateDetail/DealHeader/DealHeader.js
  src/pages/RealEstateDetail/RealEstateDetail.js
Labels: Status: 리뷰 요청

#12 [22기 장운서]투자하기 페이지 레이아웃 1차 commit
  src/pages/Apply/Apply.js
  src/pages/Apply/ApplyInput/ApplyInput.js
  src/pages/Apply/ApplyInput/CheckImg.svg
  src/pages/RealEstateDetail/KakaoMapScript.js
Labels: Status: 리뷰 요청

#22 [22기 정빛열음] config 수정
  src/config.js
Labels: Status: 리뷰 요청

#15 [22기 황소미] 마이페이지 > 투자요약 코멘트 사항 수정
  public/data/history.json
  public/data/investmentSummaryView.json
  public/data/overview.json
  public/data/portfolioView.json
  public/image/x.png
  public/index.html
  src/pages/MyPage/Overview/ChartOption.js
  src/pages/MyPage/Overview/InvestContent.js
  src/pages/MyPage/Overview/Modal.js
  src/pages/MyPage/Overview/Overview.js
  src/pages/MyPage/Overview/OverviewLeftBottom.js
  src/pages/MyPage/Overview/OverviewRightBottom.js
  src/pages/MyPage/Overview/OverviewRightTop.js
  src/pages/MyPage/Overview/PortfolioTable.js
  src/utilities/utils.js
Labels: Status: 리뷰 요청

#19 [22기 정빛열음] Add: 로그인 후 네비게이션 바 완료
  src/components/Nav/Nav.js
  src/components/Nav/SignIn/SignIn.js
  src/components/Nav/SignOut/SignOut.js
  src/components/Nav/SubNav/SubNav.js
  src/components/Nav/SubNav/navTabList.js
  src/utilities/token.js
Labels: Status: Accepted

#20 [22기 정빛열음] Add: 필터 기능 및 체크박스 완료
  public/data/individual.json
  src/components/StyledCheckBox/StyledCheckBox.js
  src/pages/Individual/EmptyIndividual/EmptyIndividual.js
  src/pages/Individual/Individual.js
  src/pages/Individual/IndividualFilter/IndividualFilter.js
  src/pages/Individual/IndividualFilter/IndividualFilterBar/IndividualFilterBar.js
  src/pages/Individual/IndividualFilter/filterRange.js
  src/pages/Individual/IndividualItem/IndividualItem.js
  src/pages/Individual/InvestmentBtn/InvestmentBtn.js
Labels: Status: 리뷰 요청

#23 [22기 황소미] 카카오 env 오류 수정
  public/index.html
Labels: Status: Accepted, Status: Conflict 해결 요청

#27 [22기 황소미] config 2차 수정...[urgent...]
  src/config.js
Labels: Status: 리뷰 요청

#24 [22기 정빛열음] 토큰 키 수정
  src/utilities/token.js
Labels: Status: 리뷰 요청

#18 [22기 정빛열음] Add: 프로덕트 카드 그래프, 메인 캐러셀 무한 롤링 및 오토 무브 완료
  src/components/Nav/Nav.js
  src/components/ProductList/ProductItem/ProductItem.js
  src/components/ProductList/ProductList.js
  src/pages/Main/AccBox/AccBox.js
  src/pages/Main/Main.js
  src/pages/Main/MainSlide/MainSlide.js
  src/pages/Main/MainSlide/MainSlideDot/MainSlideDot.js
  src/pages/Main/MainSlide/MainSlideItem/MainSlideItem.js
  src/pages/Main/MainSlide/slideBgColor.js
  src/pages/RealEstate/PastProductList/PastProductItem/PastProductItem.js
  src/pages/RealEstate/PastProductList/PastProductList.js
  src/pages/RealEstate/RealEstate.js
Labels: Status: 리뷰 요청

#31 [22기 황소미] Index.html 수정(URGENT)
  public/index.html
Labels: Status: Accepted

#32 [22기 황소미] config 수정(URGENT...!!!)
  src/config.js
Labels: Status: Accepted

#34 [22기 정빛열음] Modify: 메인 슬라이드 개수 변경
  src/pages/Main/Main.js
  src/pages/Main/MainSlide/MainSlide.js
  src/pages/Main/MainSlide/MainSlideItem/MainSlideItem.js
  src/pages/Main/MainSlide/slideBgColor.js
Labels: Status: Accepted

#26 [22기 정빛열음] Add: 로그아웃
  src/components/Nav/SignIn/SignIn.js
  src/utilities/token.js
Labels: Status: 리뷰 요청

#28 [22기 황소미] 투자요약 페이지 서버통신 완료 및 모달창 업그레이드
  src/pages/MyPage/Overview/InvestContent.js
  src/pages/MyPage/Overview/Modal.js
  src/pages/MyPage/Overview/Overview.js
  src/pages/MyPage/Overview/OverviewRightBottom.js
  src/pages/MyPage/Overview/OverviewRightTop.js
  src/pages/MyPage/Overview/PortfolioTable.js
Labels: Status: Accepted

#30 [22기 정빛열음] Fix: pathname수정
  src/components/Nav/SubNav/navTabList.js
Labels: Status: Accepted

#29 [22기 정빛열음] 메인 페이지 누적 정보 완료
  src/pages/Main/AccBox/AccBox.js
  src/pages/Main/Main.js
Labels: Status: Accepted

#37 [22기 정빛열음] Add: 전체 투자 버튼
  src/components/ProductList/ProductList.js
Labels: Status: 리뷰 요청

#36 [22기 정빛열음] Modify: 컬러 수정
  src/components/ProductList/ProductItem/ProductItem.js
  src/pages/Individual/IndividualItem/IndividualItem.js
  src/utilities/utils.js
Labels: Status: Accepted

#25 [22기 황소미] 마이페이지 투자내역 페이지네이션 기능 구현 및 통신 완료
  src/pages/MyPage/History/History.js
  src/pages/MyPage/History/HistoryHeader.js
  src/pages/MyPage/History/HistoryTable.js
  src/pages/MyPage/History/Pagination.js
Labels: Status: Accepted

#16 [22기 장운서]부동산 상품디테일 페이지 슬라이드 기능 구현 완료
  src/pages/RealEstateDetail/DealHeader/DealHeader.js
  src/pages/RealEstateDetail/Slide/Slide.js
Labels: Status: Accepted

#39 [22기 정빛열음] Modify: 투자하기 버튼 기능 수정
  src/components/ProductList/ProductList.js
  src/pages/Individual/InvestmentBtn/InvestmentBtn.js
Labels: Status: Accepted

#38 [22기 정빛열음] fetchData 함수 구현 완료
  src/pages/Individual/Individual.js
  src/pages/Main/Main.js
  src/pages/RealEstate/RealEstate.js
  src/utilities/fetch.js
Labels: Status: Accepted

#40 [22기 정빛열음] Add: 투자 완료 라벨 생성
  src/components/ProductList/ProductItem/InvestedLabel/InvestedLabel.js
  src/components/ProductList/ProductItem/ProductItem.js
Labels: Status: 수정 요청

#17 [22기 장운서] 상품디테일 페이지 서버와 데이터 연결 중
  .vscode/settings.json
  public/index.html
  src/config.js
  src/pages/RealEstateDetail/Chart/lineChart.js
  src/pages/RealEstateDetail/Chart/pieChart.js
  src/pages/RealEstateDetail/ControllerWrap/ControllerWrap.js
  src/pages/RealEstateDetail/Deal/Deal.js
  src/pages/RealEstateDetail/Deal/DealStyle.js
  src/pages/RealEstateDetail/Deal/DealWrap/DealDetail.js
  src/pages/RealEstateDetail/Deal/DealWrap/DealInfo.js
  src/pages/RealEstateDetail/Deal/DealWrap/DealSecurity.js
  src/pages/RealEstateDetail/DealHeader/DealHeader.js
  src/pages/RealEstateDetail/KakaoMapScript.js
  src/pages/RealEstateDetail/RealEstateDetail.js
  src/pages/RealEstateDetail/Slide/Slide.js
Labels: Status: Accepted

#41 [22기 정빛열음] URGENT: removeToken, 오류 수정
  src/components/Nav/SignIn/SignIn.js
  src/pages/Main/Main.js
  src/pages/RealEstateDetail/Slide/Slide.js
  src/utilities/token.js
Labels: Status: Accepted

#42 [22기 장운서] 바뀐 데어티값 type 교체
  src/pages/RealEstateDetail/ControllerWrap/ControllerWrap.js
  src/pages/RealEstateDetail/RealEstateDetail.js
  src/pages/RealEstateDetail/Slide/Slide.js
Labels: Status: Accepted

#44 [22기 정빛열음] Modify: 수정 사항 수정
  src/components/ProductList/ProductItem/ProductItem.js
  src/components/ProductList/ProductList.js
  src/pages/Individual/Individual.js
  src/pages/Individual/IndividualItem/IndividualItem.js
  src/pages/Individual/InvestmentBtn/InvestmentBtn.js
  src/pages/Main/Main.js
  src/pages/Main/MainSlide/MainSlide.js
  src/pages/Main/MainSlide/MainSlideItem/MainSlideItem.js
  src/pages/RealEstate/PastProductList/PastProductItem/PastProductItem.js
  src/pages/RealEstate/PastProductList/PastProductList.js
Labels: Status: 리뷰 요청

#45 [22기 정빛열음] subNav 조건 수정
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청

#46 [22기 황소미] Feature/history page 페이지네이션
  src/pages/MyPage/History/History.js
  src/pages/MyPage/History/HistoryHeader.js
  src/pages/MyPage/History/Pagination.js
  src/pages/MyPage/Overview/Overview.js
Labels: Status: 리뷰 요청

#47 [22기 정빛열음] Modify: fetch 시 넘겨주는 헤더 수정
  src/pages/Individual/Individual.js
  src/pages/Main/Main.js
  src/pages/RealEstate/RealEstate.js
Labels: Status: 리뷰 요청

#48 [22기 황소미] 로고 수정
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청

#33 [22기 장운서]투자하기 모두체크하기 구현중
  src/config.js
  src/pages/Apply/Apply.js
  src/pages/Apply/ApplyInput/ApplyInput.js
Labels: Status: 리뷰 요청
